version: '3.9'

networks:
  player-network:
    name: player-services

services:
  player-database:
    image: postgres:11
    container_name: player-database
    ports:
      - "5435:5432"
    volumes:
      - ${POSTGRESQL_PATH}:/var/lib/postgresql/data
    networks:
      - player-network
    environment:
      TZ: America/Fortaleza
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    restart: always

  player-service:
    build: ../
    container_name: player-service
    ports:
      - "8085:8080"
    networks:
        - player-network
    depends_on:
        - player-database
    env_file:
      - .env
    restart: always
